/* Generated By:JavaCC: Do not edit this line. parserHuracanesConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserHuracanesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IdHuracan = 1;
  /** RegularExpression Id. */
  int NombreHuracan = 2;
  /** RegularExpression Id. */
  int VelocidadHuracan = 3;
  /** RegularExpression Id. */
  int Fecha = 4;
  /** RegularExpression Id. */
  int Latitud = 5;
  /** RegularExpression Id. */
  int Longitud = 6;
  /** RegularExpression Id. */
  int Data = 7;
  /** RegularExpression Id. */
  int DIA = 8;
  /** RegularExpression Id. */
  int MES = 9;
  /** RegularExpression Id. */
  int ANIO = 10;
  /** RegularExpression Id. */
  int HORA = 11;
  /** RegularExpression Id. */
  int SIGNOMENOS = 12;
  /** RegularExpression Id. */
  int COMA = 13;
  /** RegularExpression Id. */
  int LETRAS = 14;
  /** RegularExpression Id. */
  int PUNTO = 15;
  /** RegularExpression Id. */
  int NUMERO = 16;
  /** RegularExpression Id. */
  int NUMEROFILAS = 17;
  /** RegularExpression Id. */
  int ESPACIO = 18;
  /** RegularExpression Id. */
  int RECID = 19;
  /** RegularExpression Id. */
  int ESTADOHURACAN = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IdHuracan>",
    "<NombreHuracan>",
    "<VelocidadHuracan>",
    "<Fecha>",
    "<Latitud>",
    "<Longitud>",
    "<Data>",
    "<DIA>",
    "<MES>",
    "<ANIO>",
    "<HORA>",
    "<SIGNOMENOS>",
    "\",\"",
    "<LETRAS>",
    "\".\"",
    "<NUMERO>",
    "<NUMEROFILAS>",
    "<ESPACIO>",
    "<RECID>",
    "<ESTADOHURACAN>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
  };

}
